/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LevelTaxesRouteImport } from './routes/level.taxes'
import { Route as LevelBenefitsRouteImport } from './routes/level.benefits'
import { Route as LevelBankingRouteImport } from './routes/level.banking'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelTaxesRoute = LevelTaxesRouteImport.update({
  id: '/level/taxes',
  path: '/level/taxes',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelBenefitsRoute = LevelBenefitsRouteImport.update({
  id: '/level/benefits',
  path: '/level/benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelBankingRoute = LevelBankingRouteImport.update({
  id: '/level/banking',
  path: '/level/banking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/loading': typeof LoadingRoute
  '/onboarding': typeof OnboardingRoute
  '/level/banking': typeof LevelBankingRoute
  '/level/benefits': typeof LevelBenefitsRoute
  '/level/taxes': typeof LevelTaxesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/loading': typeof LoadingRoute
  '/onboarding': typeof OnboardingRoute
  '/level/banking': typeof LevelBankingRoute
  '/level/benefits': typeof LevelBenefitsRoute
  '/level/taxes': typeof LevelTaxesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/loading': typeof LoadingRoute
  '/onboarding': typeof OnboardingRoute
  '/level/banking': typeof LevelBankingRoute
  '/level/benefits': typeof LevelBenefitsRoute
  '/level/taxes': typeof LevelTaxesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/loading'
    | '/onboarding'
    | '/level/banking'
    | '/level/benefits'
    | '/level/taxes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/loading'
    | '/onboarding'
    | '/level/banking'
    | '/level/benefits'
    | '/level/taxes'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/loading'
    | '/onboarding'
    | '/level/banking'
    | '/level/benefits'
    | '/level/taxes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoadingRoute: typeof LoadingRoute
  OnboardingRoute: typeof OnboardingRoute
  LevelBankingRoute: typeof LevelBankingRoute
  LevelBenefitsRoute: typeof LevelBenefitsRoute
  LevelTaxesRoute: typeof LevelTaxesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level/taxes': {
      id: '/level/taxes'
      path: '/level/taxes'
      fullPath: '/level/taxes'
      preLoaderRoute: typeof LevelTaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level/benefits': {
      id: '/level/benefits'
      path: '/level/benefits'
      fullPath: '/level/benefits'
      preLoaderRoute: typeof LevelBenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level/banking': {
      id: '/level/banking'
      path: '/level/banking'
      fullPath: '/level/banking'
      preLoaderRoute: typeof LevelBankingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoadingRoute: LoadingRoute,
  OnboardingRoute: OnboardingRoute,
  LevelBankingRoute: LevelBankingRoute,
  LevelBenefitsRoute: LevelBenefitsRoute,
  LevelTaxesRoute: LevelTaxesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
